AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  covid_update

  Sample SAM Template for covid_update

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  UpdateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: update/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - S3WritePolicy: { BucketName: "ncov" }

      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)
            Enabled: true

      MemorySize: 128
      Timeout: 100
